### ISSUE TITLE
04-03 - GET /practice?mode=api

### ISSUE THREAD

**Issue by Tmoney2020** [Tmoney2020/assignments#14]
## Objectives

- Create a simple API
- Practice problem solving

## Requirements

- Create 2 endpoints, `/mumbling` and `/explosion`, that are based off of the katas,`[https://www.codewars.com/kata/mumbling](https://www.codewars.com/kata/mumbling)` and `[https://www.codewars.com/kata/digits-explosion(https://www.codewars.com/kata/digits-explosion)` respectfully.

### Explorer Mode

- [x] Create a new `webapi` api project
- [x] Create a endpoint for the `mumbling` endpoint
  - [x] Create a new Controller called `MumblingController`
  - [x] This will have one `HttpGet` method
  - [x] The method will accept a string either as a URL parameter or a query parameter. Your choice.
  - [x] This endpoint method will take the string passed to it, manipulate according to the kata [https://www.codewars.com/kata/mumbling(https://www.codewars.com/kata/mumbling) and return the result
  - [x] Have your code return the string
- [x] Create a endpoint for the `explosion` endpoint
  - [x] Create a new Controller called `ExplosionController`
  - [x] This will have one `HttpGet` method
  - [x] The method will accept a string either as a URL parameter or a query parameter. Your choice.
  - [x] This endpoint method will take the string passed to it, manipulate according to the kata
        [https://www.codewars.com/kata/digits-explosion(https://www.codewars.com/kata/digits-explosion) and return the result
  - [x] Have your code return the string

## Adventure Mode

None

## Epic Mode

None

## Resources

- Use [Insomnia](https://insomnia.rest/) for interacting with your API.

**Comment by Tmoney2020** [comment]
https://github.com/Tmoney2020/WebAPI

**Comment by gstark** [comment]
Nice work!!

**Comment by Tmoney2020** [comment]
Your homework **04-03 - GET /practice?mode=api** was marked: **Meets Expectations**


![Ring that bell!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBTQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fabcecd7c921cc4014bfcce0bd127f9e89ef3986/meets-2.gif)
> &ldquo;Ring that bell!&rdquo;
