### ISSUE TITLE
08 - 02 - Currency Converter

### ISSUE THREAD

**Issue by Tmoney2020** [Tmoney2020/assignments#29]
In this assignment, you will create a React application that will convert various currencies.

For the data, you will use the API [available here](https://ratesapi.io/)

## Objectives

- Work with an API to display data
- Work with React
- Work with the React lifecycle (`componentDidMount` with classes or `useEffect` with hooks)

## Requirements

- Use [this API documentation](https://ratesapi.io/documentation/) to build a page that allows for conversion between multiple currencies

### Explorer Mode

- [x] Create a page that loads and shows the current currency conversion rates.
- [x] Design the page yourself or use utility CSS libraries like: [Bootstrap](https://getbootstrap.com) or [Bulma](https://bulma.io/) or [Tailwind](https://tailwindcss.com/)
- [x] Use `USD` as the _base_ currency.
- [x] Allow the user to enter a currency amount (allow for decimal amounts like `42.12`) in USD.
- [x] Show the converted amount in each of the available currencies.
  - [x] Either update _as the user types_ or include a button that performs the conversion when clicked.

### Adventure Mode

- [x] Allow the user to choose a new base currency other than USD.
- [x] Allow the user to use a specific day in the past.
  - [HINT](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date)
  - Fetch the conversion rates for that day.
  - Show the updated conversion rates and converted amount.

### Epic Mode

- [ ] Use react router to allow the user to specify the base currency in the URL

**Comment by Tmoney2020** [comment]
https://github.com/Tmoney2020/currency-converter

**Comment by Tmoney2020** [comment]
Your homework **08 - 02 - Currency Converter** was marked: **Exceeds Expectations**


![Niiiiiiiiice!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBTdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0f7e0d5535291cc82f410da4761392ed248ba5a6/tumblr_inline_odd2x9PvYg1raprkq_400.gif)
> &ldquo;Niiiiiiiiice!&rdquo;

**Comment by gstark** [comment]
Nicely done!

You should be able to use your array of currencies to remove the duplicate in code like this: https://github.com/Tmoney2020/currency-converter/blob/master/src/App.jsx#L173

But very nicely done!
